### PR TITLE
Update for Meteor 3

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Following #91, this is an attempt to quickly update the main package for Meteor 3.

### CODE REVIEW

**Comment by jankapunkt** [comment]
@serut can you please take a look at this? It's really important, because otherwise people can't upgrade to Meteor 3

**Comment by serut** [comment]
Ok, but it means the package may not work at all on Meteor 3. Publishing a not working version is not great, did you tryed to run tests ? The test creates a Meteor app and add the local package inside the build so you can test if it works.

Sadly, the CI (travis..) is not working anymore..

**Comment by jankapunkt** [comment]
@serut I can easily add GitHub ci if you want

**Comment by serut** [comment]
Feel free yes

**Comment by jankapunkt** [comment]
@serut see #93

**Comment by jankapunkt** [comment]
@StorytellerCZ if testing locally the setup command should be changed to

```json
    "setup-test": "rm -rf ./someapp && meteor create --release 3.0.1 --bare someapp && cd someapp && cp ../.coverage.json . && meteor npm i --save puppeteer && mkdir packages && ln -s ../../ ./packages/meteor-coverage",
```

**Comment by serut** [comment]
Now there is CI on every MR, can you try to fix tests [jankapunkt](https://github.com/jankapunkt) ? 
I can give write access to this repository if you want to.

**Comment by jankapunkt** [comment]
hi @serut yes, isn't that what you want - have a mr being checked if it passes lint and tests? I can modify but I would have to know what you intend it to work. Wrie access would be great as I already found a few more things to be updated for Meteor 3 (Webapp, HTTP package etc.)

**Comment by serut** [comment]
Oh sorry, I was wondering if you could check why the build is not working. It's nice to have github actions but better to have tests running well .. It tells `npm ci` cannot be run without ` npm-shrinkwrap.json` file...

see https://github.com/serut/meteor-coverage/actions/runs/9980609619/job/27582397140

**Comment by jankapunkt** [comment]
@serut can you please re-invite me? I was on vacation and the link expired. I can look into the action logs as member. Usually this is just a missing package-lock.json or deleting and reinstalling npm deps. Should not be hard to fix. After that I can work on 3.0 compat.

**Pull request merged**
